%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 554.154462
Camera1.fy: 558.489918
Camera1.cx: 661.197510
Camera1.cy: 377.243085

Camera1.k1: -0.233132
Camera1.k2: 0.031429
Camera1.p1: -0.000694
Camera1.p2: 0.000292

Camera.width: 1280
Camera.height: 720

Camera.newWidth: 853
Camera.newHeight: 480

# Camera frames per second 
Camera.fps: 40

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.0235027,  -0.03267351,  0.9991897,  -0.00011162,
         -0.99946845,  0.02181935,  0.02422275, -0.00045193,
         -0.02259311, -0.99922788, -0.03214332, -0.04526275,
         0.,          0.,          0.,          1.        ]

# IMU noise
#IMU.NoiseGyro: 8.726e-05 # Kakutei H7
#IMU.NoiseAcc: 3.922e-03 # Kakutei H7
IMU.NoiseGyro: 0.0008982319103847968 # Kalibr Discrete
IMU.NoiseAcc: 0.052511134073349744 # Kalibr Discrete
IMU.GyroWalk: 2.301e-05 # Kakutei H7
IMU.AccWalk: 5.058e-04 # Kakutei H7
# IMU.NoiseGyro: 8.726e-01 # Kakutei H7
# IMU.NoiseAcc: 3.922e-01 # Kakutei H7
# IMU.GyroWalk: 2.301e-01 # Kakutei H7
# IMU.AccWalk: 5.058e-01 # Kakutei H7
IMU.Frequency: 150.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 4

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

